### ISSUE TITLE
No `cited_by` data?

### ISSUE THREAD

**Issue by leflix311** [cverluise/SciCit#2]
Cyril, Gaétan
Great job, I am just looking into it. Have two questions:
1) Do I understand correctly that the present beta version of dataset contains only bibliographic info on NPL, and no patent identifier? Because I can find none (correct me if I am wrong). That is, it is about what's cited, but not who's citing
2) Do NPL citations come only from search reports, or do they also include in-text citations? From your e-mail it is not entirely clear
Thanks and congratulations again
Francesco

**Comment by cverluise** [comment]
Dear @leflix311,

thanks for your kind words! 

> 1. Do I understand correctly that the present beta version of dataset contains only bibliographic info on NPL, and no patent identifier? Because I can find none (correct me if I am wrong). That is, it is about what's cited, but not who's citing

Yes, you can get back to the citing document. 

The `npl_publn_id` in our database is the `NPL_PUBLN_ID` reported in the Patstat.tls214 table. Using this key, you can get back to the citing patents (aka `PAT_PUBLN_ID`) using the `CITED_NPL_PUBLN_ID` in the Patstat.tls212 table. 

That being said, this is definitely the kind of data-gym that we want to avoid to the end-user. The database should be self-sufficient. Actually, as this is a `1:n` relationship and that we would like to avoid the database to expand dramatically, we are still looking at an efficient and user-friendly way to do it. So, definitely, would you have any suggestion, we will consider it carefully.  

> 2. Do NPL citations come only from search reports, or do they also include in-text citations? From your e-mail it is not entirely clear

The first release include only front page npl citations, not in-text citations as they are not reported in the DOCDB database. It seems that this is gradually evolving but there is no plan for backfiles. Anyway, from the `NPL_PUBLN_ID` we can get the `CITN_ORIGIN` (Patstat.tls212 table) which gives you the origin of the citation (APP, SEA, etc). You are right, this information should also be reported in the final dataset. 

That being said, we are also working on in-text patent (AND patent) citations using the same pipeline techno/pipeline for the US. We are currently processing US patent full-texts to extract, parse and consolidate in-text patent and NPL citations. We are also planning to do it for other major patent offices. Would you have any suggestion on the top priorities, let us know. 

Hope it helps, 

Cyril

**Comment by cverluise** [comment]
Hello @leflix311 ,

I have just updated the beta. 

You will now find two additional (nested) columns:

- `cited_by.origin`: origin of the citation (SEA, APP, OPP, etc) where the code refers to PatStat `CITN_ORIGIN`. I report the codes description below.
<details>

- `APP`: citations introduced by the applicant
- `SEA`: citations introduced during search (from Search Report)
- `ISR`: citations from the International Search Report
- `SUP`: citations from the Supplementary Search Report
- `PRS`: "PRe-Search" citations (available before official publication)
- `EXA`: citations introduced during examination
- `OPP`: citations introduced during opposition (citations by opponent published with a European Patent Specification (EP-B2))
- `APL`: citations introduced when filed for appeal by applicant / proprietor / patentee
- `FOP` citations introduced when filed opposition by any third party after the publication of a European Patent Specification (EP- B1)
- `TPO` citations introduced because of Third Party Observations (Art 115 EPC) CH2 citations introduced during the Chapter 2 phase of the PCT

</details>

- `cited_by.publication_number`: publication number of citing patents (e.g. EP-0768779-A3)

Does it help?

Cyril

**Comment by cverluise** [comment]
Hello, 

This is now streamlined. 

You will find the variables defined above with the following schema in all V0+ releases:

Field name | Type | Mode | Description
-- | -- | -- | --
cited_by | RECORD | REPEATED |  
cited_by. origin | STRING | REPEATED | Origin of the citation (e.g. APPlicant, SEArch report, etc)
cited_by. publication_number | STRING | REPEATED | DOCDB publication number of citing patent(s)

I close this issue, feel free to re-open it if needed

Cheers
