### ISSUE TITLE
Date in the IDNO column instead of WHEN

### ISSUE THREAD

**Issue by SuperMayo** [cverluise/SciCit#4]
## How to reproduce the behaviour
```mysql
SELECT a.npl_publn_id,
       a.idno,
       a.title_main_a,
       a.when
FROM `npl-parsing.patcit.beta` a
WHERE
  npl_publn_id = 12761
  OR npl_publn_id = 42574
```

Returns:

Ligne | npl_publn_id | idno | title_main_a | when |  
-- | -- | -- | -- | -- | --
1 | 12761 | 1988-08-02 | [Test procedure and specifications for component susceptibility to electrostatic discharges](https://ieeexplore.ieee.org/document/14111) | null |  
2 | 42574 | 1988-03-07 | [QuickSilver distributed file services: an architecture for horizontal growth](https://ieeexplore.ieee.org/document/4798) | null |  

## Comments

I am not sure about the nature of the `idno` column as I cannot see any pattern accross observations.
But as you can see, sometimes the date is wrongly populated in this column (for proof I have included links). In those two cases it is an IEEE conference paper so maybe there is a pattern.

**Comment by cverluise** [comment]
hello @SuperMayo ,

thanks. 

You are right.

Fyi, the `idno` field normally refers to "the document-specific identifier" and can endorse different types (e.g. DOI, ISSN, ISSNe, etc). When the type is specified, a specific field has been created, that's why the database include fields like `DOI`, `ISSN` etc. When this is not the case, the `idno` is left in `idno`.

In short, this is a parsing issue. 

I'm currently not sure to know what would be the best solution. Definitely, there are many options involving different levels of resource. Main options are the following.

1. *Ad hoc solution, _short-term_*: type checking and ad-hoc re-attribution and the type in `idno` is `date`. Definitely not my favourite, but might be a quick patch. 

2. *Training the Grobid model, _medium-term_*: the parsing step is implemented by the great Grobid library (see doc [here](https://grobid.readthedocs.io/)) which models can be trained. The long term solution might well be to leverage known issues such as this one to improve the current model. This is definitely my favourite solution - yet should be done carefully.

Any other idea @SuperMayo ?

Hope it helps.

**Comment by SuperMayo** [comment]
What about the doi ? In those two examples, the doi is well identified such that you should be able to populate the `when` column with the right value.

**Comment by cverluise** [comment]
hmmm, you are right. Will investigate that. Thanks!

**Comment by cverluise** [comment]
At this point, we do the following:

1. flag the issue (#4) whenever the idno has a date compatible format ("%Y" or  "%Y-%M" or "%Y-%M-%D")
2. report the detected issue (if any) in the field `Issues` 
3. two cases:

- if `when` has a date compatible format, we report the when.year value in `year`, ie when keeps the priority
-  else, we report the idno.year in `year`

I close the issue, feel free to re-open it if needed.

Cheers
